# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Fabric API
fabric_version=0.152.2+26.2
# Mod Properties
mod_version=3.12.3
maven_group=net.spellcraftgaming.rpghud
archivesName=[26.2][Fabric] RPG-HUD
# Dependencies
