# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version = 3.13.0
maven_group = net.spellcraftgaming.rpghud
archives_base_name = [1.21.11][Fabric] RPG-HUD

# Dependencies
fabric_version=0.149.0+26.1.2