# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="GNU GPLv3"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="rpghud" #mandatory

# The version number of the mod
version="3.13" #mandatory

# A display name for the mod
displayName="RPG-HUD" #mandatory

# The authors of the mod, displayed in the mod UI (optional)
authors="Raelzaryn"

# The description text for the mod (multi line!) (#mandatory)
description='''
This mod changes the way the HUD is rendered and adds several new functionalities and styles (mainly RPG-like styles)
'''
